# Generated by Django 4.2.4 on 2024-08-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caad_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_cnic', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, primary_key=True, serialize=False)),
                ('admin_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('admin_id', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('admin_password', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='loginproforma',
            options={'managed': True},
        ),
    ]
