# Generated by Django 4.2.4 on 2024-08-08 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caad_api', '0002_admin_alter_loginproforma_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginproforma',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='ncpdues',
            table='ncpduess',
        ),
    ]
