from django.urls import path
from caad_api import views

urlpatterns = [
    path('student', views.studentApi),
    path('student/<str:std_cnic>', views.studentApi),
    path('studentreg', views.studentRegistrationApi),
    path('studentreg/<str:std_cnic>', views.studentRegistrationApi),
    path('internships', views.InternshipsApi),
    path('internships/<int:internship_id>', views.InternshipsApi),
    path('evaluation', views.EvaluationProformaApi),
    path('evaluation/<int:evaluation_id>', views.EvaluationProformaApi),
    path('caadevaluation', views.CaadEvaluationVerificationApi),
    path('caadevaluation/<int:caad_evaluation_id>', views.CaadEvaluationVerificationApi),
    path('caadclearance', views.CaadClearanceVerificationApi),
    path('caadclearance/<int:caad_clearance_id>', views.CaadClearanceVerificationApi),
    path('publications', views.NcpPublicationsApi),
    path('publications/<int:ncppublications_id>', views.NcpPublicationsApi),
    path('clearance', views.ClearancePerformaApi),
    path('clearance/<int:clearance_id>', views.ClearancePerformaApi),
    path('dues', views.NcpDuesApi),
    path('dues/<int:dues_id>', views.NcpDuesApi),
    path('caadreg', views.CaadRegistrationVerificationApi),
    path('caadreg/<int:caad_registration_verification>', views.CaadRegistrationVerificationApi),
    path('identity', views.IdentitycardProformaApi, name='IdentitycardProformaApi'),  
    path('identity/<int:id>', views.IdentitycardProformaApi, name='IdentitycardProformaApi'),
    path('caadidentity', views.CaadIdentityApi, name='CaadIdentityApi'),  
    path('caadidentity<int:id>', views.CaadIdentityApi, name='CaadIdentityApi'),  
    path('latesitting', views.LateSittingApi, name='LateSittingApi'),  
    path('latesitting/<int:id>', views.LateSittingApi, name='LateSittingApi'), 
    path('caadlatesitting', views.CaadLatesittingVerificationApi, name='CaadLatesittingVerificationApi'),  
    path('caadlatesitting/<int:caad_latesitting_id>', views.CaadLatesittingVerificationApi, name='CaadLatesittingVerificationApi'), 
    path('transport', views.TransportMemFormApi, name='TransportMemFormApi'),  
    path('transport/<int:id>', views.TransportMemFormApi, name='TransportMemFormApi'),
    path('transportsect', views.CaadTransportVerificationApi, name='CaadTransportVerificationApi'),  
    path('transportsect/<int:id>', views.CaadTransportVerificationApi, name='CaadTransportVerificationApi'), 
    path('accomodation', views.AccomodationProformaApi, name="AccomodationProformaApi"),
    path('accomodation/<int:id>', views.AccomodationProformaApi),
    path('accomodationtype', views.AccomodationTypeApi, name="AccomodationTypeApi"),
    path('accomodationtype/<int:id>', views.AccomodationTypeApi),
    path('caadaccomodation', views.CaadAccomodationApi, name="CaadAccomodationApi"),
    path('caadaccomodation/<int:id>', views.CaadAccomodationApi),
    path('ncpaccomodationchk', views.NcpCheckAccApi, name="NcpCheckAccApi"),
    path('ncpaccomodationchk/<int:id>', views.NcpCheckAccApi),
    path('ncpaccomodationapp', views.NcpApprovalAccApi, name="NcpApprovalAccApi"),
    path('ncpaccomodationapp/<int:id>', views.NcpApprovalAccApi),
    path('extension', views.ExtensionProformaApi, name="ExtensionProformaApi"),
    path('extension/<int:id>', views.ExtensionProformaApi),
    path('caadextension', views.CaadExtensionVerificationApi, name="CaadExtensionVerificationApi"),
    path('caadextension/<int:id>', views.CaadExtensionVerificationApi),
    path('login', views.LoginProformaApi, name="LoginProformaApi"),
    path('login/<int:id>', views.LoginProformaApi),
    path('itlogin', views.ItDeptLoginApi, name="ItDeptLoginApi"),
    path('itlogin/<int:id>', views.ItDeptLoginApi), 
]